// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantFaves.Models.Data;

#nullable disable

namespace RestaurantFaves.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231117001448_initialization")]
    partial class initialization
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurantFaves.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("orderAgain")
                        .HasColumnType("bit");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<string>("restaurant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "Whole Grain Tuscan Fresca",
                            orderAgain = true,
                            rating = 4,
                            restaurant = "Olive Garden"
                        },
                        new
                        {
                            id = 2,
                            description = "McChicken",
                            orderAgain = false,
                            rating = 3,
                            restaurant = "McDonalds"
                        },
                        new
                        {
                            id = 3,
                            description = "Lobster Thermidor",
                            orderAgain = true,
                            rating = 5,
                            restaurant = "Red Lobster"
                        },
                        new
                        {
                            id = 4,
                            description = "Mac & Cheese",
                            orderAgain = false,
                            rating = 2,
                            restaurant = "Olive Garden"
                        },
                        new
                        {
                            id = 5,
                            description = "Big Mac",
                            orderAgain = true,
                            rating = 4,
                            restaurant = "McDonalds"
                        },
                        new
                        {
                            id = 6,
                            description = "Oysters",
                            orderAgain = false,
                            rating = 3,
                            restaurant = "Red Lobster"
                        },
                        new
                        {
                            id = 7,
                            description = "Spaghetti",
                            orderAgain = true,
                            rating = 5,
                            restaurant = "Olive Garden"
                        },
                        new
                        {
                            id = 8,
                            description = "McSalad",
                            orderAgain = false,
                            rating = 1,
                            restaurant = "McDonalds"
                        },
                        new
                        {
                            id = 9,
                            description = "Shrimp Alfredo",
                            orderAgain = true,
                            rating = 4,
                            restaurant = "Red Lobster"
                        },
                        new
                        {
                            id = 10,
                            description = "Breadsticks",
                            orderAgain = false,
                            rating = 3,
                            restaurant = "Olive Garden"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
